[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

[[redirects]]
  from = "/api/*"
  to = "https://lihaxa-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
